# These configuration options are currently in configs/default.yaml
BASILISK_SIMULATION:
  deltaT: 10 # Solver time step [seconds]
  useSphericalHarmonics: true
  useExponentialDensityDrag: true
  useSRP: true
  override_skf_initial_state: false