# These configuration options are currently in configs/default.yaml
BASILISK_SIMULATION:
  deltaT: 50 # Solver time step [seconds]
  sphericalHarmonicsDegree: 4 # int
  useSphericalHarmonics: true
  useExponentialDensityDrag: true
  useSRP: false
  useSun3rdBody: true 
  useMoon3rdBody: true
  override_skf_initial_state: false