# These configuration options are currently in configs/default.yaml
BASILISK_SIMULATION:
  deltaT: 10 # Solver time step [seconds]
  useSphericalHarmonics: true
  show_progress_bar: true
  override_skf_initial_state: false