# consider adding simulations_ro_run: [basilisk, skkyfiled] 
# ... as a way to specify which simulations to run

# Global simulation configuration settings
SIMULATION:
  startTime: "02.04.2025 12:00:00" # UTC time
  simulationDuration: 24.0          # hours
  tle_export_path: "data/tle_files/"

# Plotting options
PLOTTING:
  show_plots: true
  save_plots: false
  save_path: ./plots

# Global satellites and their TLE data
SATELLITES:
  satellite1:
    name: "TestSat-1"
    tle_line1: "1 25544U 98067A   20264.54791667  .00016717  00000-0  10270-3 0  9000" # Position and velocity @ inital epoch will be calculated from TLE
    tle_line2: "2 25544  51.6434 247.4627 0007417 130.5364 329.6786 15.49315339245716"
  satellite2: 
    name: "TestSat-2"
    tle_line1: "1 25544U 98067A   20264.54791667  .00016717  00000-0  10270-3 0    9000" # Position and velocity @ inital epoch will be calculated from TLE
    tle_line2: "2 25544  60.6434 247.4627 0007417 130.5364 329.6786 15.49315339245716"

# Skyfield specific settings
SKYFIELD:
  config_path: configs/overrides/skyfield.yaml

# Basilisk specific settings
BASILISK:
  config_path: configs/overrides/basilisk.yaml

