# Global simulation configuration settings
SIMULATION:
  startTime: "23.10.2025 22:19:30" # UTC time
  simulationDuration: 336.0 # hours
  tle_export_path: "data/tle_files/" # TODO: move to Config_def
  use_old_skf_data: true # Skip Skyfield simulation (used when you want to use the same SGP4 baseline to compare against multiple Basilisk runs)
  old_skf_data_timestamp: "20251208_134701" # Timestamp WITHOUT "_skf" at the end

# Plotting options
PLOTTING:
  show_plots: false
  save_plots: true
  bypass_sim_to_plot: true
  data_timestamp_to_plot: "20251129_015711" # Only plots this data if bypass_sim_to_plot == true
  plot_prev_sim: false # TODO: NOT IMPLEMENTED. Also, 'implement func that skips simulations if this is true

# Global satellites and their TLE data
# Satellite #1 will be considered as the formation Chef/Leader satellite 
SATELLITES:
  satellite1:
    name: "HYPSO-1"             
    tle_line1: "1 51053U 22002BX  25296.93021535  .00034531  00000+0  64114-3 0  9996"
    tle_line2: "2 51053  97.3166   6.7052 0004161  83.3535 276.8189 15.48851464210108" 
    m_s: 6.0  # [kg] Satellite mass
    C_D: 3  # Drag coefficient
    A_D: 0.06 # [m^2] Cross-section area perpendicular to the velocity
    C_R: 1.0  # Radiation pressure coefficient (0 reflecting, 1 absorbing)
    A_srp: 0.06 # [m^2] Cross-section area perpendicular to the Sun-vector 
  satellite2:
    name: "HYPSO-1-follower"             
    tle_line1: "1 51053U 22002BX  25296.93021535  .00034531  00000+0  64114-3 0  9996"
    tle_line2: "2 51053  97.3166   6.7052 0004161  83.3535 266.8189 15.48851464210108"    
    m_s: 6.0  # [kg] Satellite mass
    C_D: 2.2  # Drag coefficient
    A_D: 0.06 # [m^2] Cross-section area perpendicular to the velocity
    C_R: 1.0  # Radiation pressure coefficient (0 reflecting, 1 absorbing)
    A_srp: 0.06 # [m^2] Cross-section area perpendicular to the Sun-vector 

# Skyfield specific settings
SKYFIELD:
  config_path: configs/overrides/skyfield.yaml

# Basilisk specific settings
BASILISK:
  config_path: configs/overrides/basilisk.yaml







    # name: "Chief"
    # tle_line1: "1 51053U 22002BX  25308.62091721  .00030597  00000+0  55283-3 0  9995"    
    # tle_line2: "2 51053  97.3162  18.5553 0003625  48.0410 312.1150 15.49656913211910"  
    # name: "Follower"
    # tle_line1: "1 60531U 24149BR  25308.17016602  .00005181  00000+0  45510-3 0  9998"    
    # tle_line2: "2 60531  97.7074  22.6954 0001936  74.1043 286.0392 14.97007322 66363" 
   

  # satellite1:
  #   name: "TestSat-1"
  #   tle_line1: "1 25544U 98067A   20264.54791667  .00016717  00000-0  10270-3 0  9000"
  #   tle_line2: "2 25544  51.6434 247.4627 0007417 130.5364 329.6786 15.49315339245716"
  # satellite2: 
  #   name: "TestSat-2"
  #   tle_line1: "1 25544U 98067A   20264.54791667  .00016717  00000-0  10270-3 0    9000"
  #   tle_line2: "2 25544  60.6434 247.4627 0007417 130.5364 329.6786 15.49315339245716"

  # satellite1: 
  #   name: "GSAT0201 (GALILEO 5)"    
  #   tle_line1: "1 40128U 14050A   25293.02891527 -.00000069  00000+0  00000+0 0  9994"
  #   tle_line2: "2 40128  49.1381 283.2505 1642820 170.2404 193.3914  1.85519627 73867"
  # satellite2: 
  #   name: GSAT0202 (GALILEO 6)    
  #   tle_line1: "1 40129U 14050B   25292.20739736 -.00000067  00000+0  00000+0 0  9995"
  #   tle_line2: "2 40129  49.1552 282.3666 1643429 170.9672 192.3990  1.85520331 76013"


